sudo: required
dist: xenial
language: cpp

script:
  - gcc --version
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-7 CC=gcc-7
      addons:
        apt:
          packages:
            - gcc-7
            - g++-7
            - p7zip-full
            - libgl1-mesa-dev
          sources: &sources
            - ubuntu-toolchain-r-test
        env:
          - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.0-xenial
  - sudo apt-get update -qq
  - eval "${MATRIX_EVAL}"

      
install:
  - sudo apt-get -y install qt512-meta-minimal
  - cd  /opt
  - wget http://download.qt.io/official_releases/qtcreator/4.8/4.8.2/qt-creator-opensource-src-4.8.2.tar.gz
  - tar -xf ./qt-creator-opensource-src-4.8.2.tar.gz
  - wget http://download.qt.io/official_releases/qtcreator/4.8/4.8.2/installer_source/linux_gcc_64_rhel72/qtcreator.7z
  - 7z x -y qtcreator.7z -o"qtcreator"
      
notifications:
  email:
    on_success: never
    on_failure: always
script:
  - source /opt/qt512/bin/qt512-env.sh
  - cd $TRAVIS_BUILD_DIR/
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - git submodule update --init --recursive --remote
  - cd $TRAVIS_BUILD_DIR/3rd-party
  - chmod +x ./src/0build_googletest.sh
  - chmod +x ./src/0build_qhttp.sh
  - ./build_third_party.sh
  - cd $TRAVIS_BUILD_DIR/collaborativeEditingPlugin
  - touch qt_deps.pri
  - echo "QTC_SOURCE = /opt/qt-creator-opensource-src-4.8.2" > qt_deps.pri
  - echo "QTC_BUILD = /opt/qt512" >> qt_deps.pri
  - echo "LIBS+=-L/opt/qtcreator/lib/qtcreator/ -L/opt/qtcreator/lib/qtcreator/plugins" >> qt_deps.pri
  - /opt/qt512/bin/qmake collaborativeEditingPlugin.pro
  - ls
  - cat ./.qmake.stash
  - make
